---
- name: centos-repo-mirror
  hosts: '{{ target }}'
  gather_facts: yes
  become: true
  become_user: root
  tasks:

    - name: EPEL
      yum:
        name: epel-release
        state: latest

    - name: nginx
      yum:
        name: nginx
        state: latest

    - name: hostname register
      shell: hostname -f
      register: hostname_cmd

    - name: centos / epel web conf
      template:
        src: "{{ item }}"
        dest: "/etc/nginx/conf.d/"
        owner: root
        group: root
        mode: u=rwX,g=rX,o=rX
      with_fileglob:
        - "web_conf/*"

    - name: nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: create sync scripts
      copy:
        src: "{{ item }}"
        dest: "/usr/local/bin/"
        owner: root
        group: root
        mode: 0750
      with_fileglob:
        - "bin/*"

    - name: run sync scripts if sync_scripts == 'yes'
      shell: /usr/local/bin/sync_repo_*
      when: sync_scripts == 'yes'

    - name: enable sync scripts cron if sync_cron == 'yes'
      cron:
        name: "sync repos"
        minute: "0"
        hour: "0"
        job: "for sync_script in /usr/local/bin/sync_repo_*; do $sync_script; done"
        user: root
      when: sync_cron == 'yes'
